import { cpSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, test } from "bun:test";

import { DENY_TERMS, PLACEHOLDER_TERMS, matchTerms } from "../src/denylist.ts";
import { runValidation } from "../src/validation/run.ts";
import type { Issue } from "../src/validation/types.ts";
import { materializeFixture } from "./helpers/tree.ts";

/**
 * One deliberately-broken tree per case, each the smallest repository that can
 * hold the mistake. `rules` is the complete set of error rules the tree may
 * raise, so a fixture that starts failing for a second reason fails the test
 * rather than passing on the one rule it was written for.
 */
interface InvalidCase {
  tree: string;
  what: string;
  rule: string;
  file: string;
  message: RegExp;
  rules?: string[];
  /**
   * Schemas copied from this repository into the tree when it is
   * materialized, so the case measures the contract itself. A committed copy
   * would go on passing after the real schema moved, which is why
   * 15-malformed-install needs a test comparing its copy with the original.
   */
  schemas?: string[];
}

const ARTICLE_SCHEMAS = ["common", "constitution-article"];

const CASES: ReadonlyArray<InvalidCase> = [
  {
    tree: "01-catalog-entry-without-directory",
    what: "a catalog entry with no directory",
    rule: "catalog.entry-without-directory",
    file: "skills/alpha",
    message: /declares skills\/alpha as authored but skills\/alpha\/ does not exist/,
  },
  {
    tree: "02-directory-without-catalog-entry",
    what: "a directory with no catalog entry",
    rule: "catalog.directory-without-entry",
    file: "skills/ghost",
    message: /catalog\.yaml declares no skills entry 'ghost'/,
  },
  {
    tree: "03-broken-link-source",
    what: "a relative link that does not resolve in the source tree",
    rule: "links.broken-source",
    file: "skills/alpha/SKILL.md",
    message: /'references\/guide\/REFERENCE\.md' does not exist/,
    // A link that is dangling at the source is dangling in the bundle too.
    rules: ["links.broken-source", "links.broken-bundle"],
  },
  {
    tree: "04-broken-link-bundle",
    what: "a link that resolves in the source tree and breaks after packaging",
    rule: "links.broken-bundle",
    file: "dist/claude-code/references/shared/references/guide/REFERENCE.md",
    message: /'references\/shared\/protocols\/review' is not in the claude-code bundle/,
  },
  {
    tree: "05-model-name-in-body",
    what: "a model name in a skill body",
    rule: "content.denylist",
    file: "skills/alpha/SKILL.md",
    message: /Denied term/,
  },
  {
    tree: "06-placeholder-text",
    what: "an unfinished marker in an authored body",
    rule: "content.placeholder",
    file: "skills/alpha/SKILL.md",
    message: /in an authored body/,
  },
  {
    tree: "07-u-calls-u",
    what: "a user-invoked skill starting another user-invoked skill",
    rule: "invocation.u-calls-u",
    file: "skills/alpha/SKILL.md",
    message: /starts user-invoked skill 'beta' directly/,
  },
  {
    tree: "08-missing-provenance",
    what: "an adapted directory with no provenance row",
    rule: "provenance.missing-adaptation",
    file: "skills/alpha",
    message: /declares provenance_origin: donor but no donor@commit:path row in provenance\/adaptations\.yaml/,
  },
  {
    tree: "09-smell-with-difficulty",
    what: "a finding whose solution space is open carrying a difficulty",
    rule: "finding.difficulty-on-open-solution-space",
    file: "templates/finding.json",
    message: /difficulty is 'mechanical'/,
  },
  {
    tree: "10-stale-approval",
    what: "an approval that no longer binds the artifact it approved",
    rule: "approval.stale",
    file: "templates/review.json",
    message: /does not inherit the previous approval/,
  },
  {
    tree: "11-decision-ticket-dispatched",
    what: "a decision ticket dispatched as implementation work",
    rule: "ticket.decision-dispatched-as-implementation",
    file: "templates/ticket.json",
    message: /carries implementation field\(s\) write_ownership/,
  },
  {
    tree: "12-self-closed-finding",
    what: "an author closing their own finding",
    rule: "finding.self-closed",
    file: "templates/finding.json",
    message: /An author may never close their own finding/,
  },
  {
    tree: "13-forged-grant",
    what: "a grant naming a charter that does not exist",
    rule: "grant.charter-hash-unknown",
    file: "templates/ticket.json",
    message: /matches no charter artifact/,
  },
  {
    tree: "14-host-key-in-canonical",
    what: "a host frontmatter key hand-written into a canonical SKILL.md",
    rule: "frontmatter.host-key-in-canonical",
    file: "skills/alpha/SKILL.md",
    message: /generated by the packager .* must not appear in a canonical SKILL\.md/,
  },
  {
    tree: "15-malformed-install",
    what: "an install file whose attached: is a bare id rather than a list",
    rule: "schemas.document-invalid",
    file: "ak.install.yaml",
    message: /install\.schema\.json: \/attached must be array/,
  },
  {
    tree: "16-case-without-fired-indicator",
    what: "a positive case with no skill-fired indicator",
    rule: "evals.no-fired-indicator",
    file: "evals/alpha/fires-on-a-named-ticket/case.yaml",
    message: /a positive case with no skill-fired indicator/,
  },
  {
    tree: "17-duplicate-case-name",
    what: "two cases sharing one name",
    rule: "evals.duplicate-case-name",
    file: "evals/alpha/first-resume/case.yaml",
    message: /case name `interrupted-publish-resumes` is also used by evals\/alpha\/second-resume\/case\.yaml/,
  },
  {
    tree: "18-description-without-command",
    what: "a user-invoked skill whose description never names its typed command",
    rule: "invocation.description-omits-command",
    file: "skills/alpha/SKILL.md",
    message: /does not name `\/ak:alpha` in its description/,
  },
  {
    tree: "19-description-without-class",
    what: "a user-invoked skill whose description names the command but not the class",
    rule: "invocation.description-omits-class",
    file: "skills/alpha/SKILL.md",
    message: /the words 'human-started' are absent/,
  },
  {
    tree: "20-first-step-not-stop",
    what: "a user-invoked skill whose first workflow step opens on the work",
    rule: "invocation.first-step-not-stop",
    file: "skills/alpha/SKILL.md",
    message: /The first step under ## Workflow .* does not name `\/ak:alpha` or say to stop/,
  },
  {
    tree: "21-article-without-source-span",
    what: "a constitution article with no source span",
    rule: "schemas.document-invalid",
    file: "templates/constitution-article.yaml",
    message: /constitution-article\.schema\.json: \(root\) must have required property 'source'/,
    schemas: ARTICLE_SCHEMAS,
  },
  {
    tree: "22-enforced-by-without-predicate",
    what: "an enforced_by entry that names no predicate",
    rule: "schemas.document-invalid",
    file: "templates/constitution-article.yaml",
    message: /constitution-article\.schema\.json: \/enforced_by\/0 must have required property 'predicate'/,
    schemas: ARTICLE_SCHEMAS,
  },
  {
    tree: "23-article-without-triggers",
    what: "an article that is not cross-cutting and names no trigger",
    rule: "schemas.document-invalid",
    file: "templates/constitution-article.yaml",
    message: /constitution-article\.schema\.json: \/triggers\/cross_cutting must be equal to constant/,
    schemas: ARTICLE_SCHEMAS,
  },
  {
    tree: "24-article-tier-outside-vocabulary",
    what: "an article whose tier is outside the three tiers",
    rule: "schemas.document-invalid",
    file: "templates/constitution-article.yaml",
    message: /constitution-article\.schema\.json: \/tier must be equal to one of the allowed values/,
    schemas: ARTICLE_SCHEMAS,
  },
];

const REPO = join(import.meta.dir, "..");

function errorsOf(tree: string, schemas: ReadonlyArray<string> = []): Issue[] {
  const root = materializeFixture(tree);
  if (schemas.length > 0) mkdirSync(join(root, "schemas"), { recursive: true });
  for (const id of schemas) {
    cpSync(join(REPO, "schemas", `${id}.schema.json`), join(root, "schemas", `${id}.schema.json`));
  }
  return runValidation(root).issues.filter((i) => i.severity === "error");
}

describe("the positive fixture", () => {
  test("a minimal well-formed tree validates clean", () => {
    const run = runValidation(materializeFixture("valid/minimal"));
    const loud = run.issues.filter((i) => i.severity !== "note");
    expect(loud.map((i) => `${i.rule} ${i.file}`)).toEqual([]);
    expect(run.ok).toBe(true);
  });

  test("the notes it does emit name the absent inputs rather than crashing", () => {
    const run = runValidation(materializeFixture("valid/minimal"));
    expect(run.issues.map((i) => i.rule)).toContain("provenance.lock-unavailable");
    expect(run.issues.map((i) => i.rule)).toContain("policy.invocation-unavailable");
  });

  test("its clean run covers schema conformance, and the positive control proves it", () => {
    // The fixture carried no `schemas/` and no `templates/` for most of its
    // life, so `checkSchemas` ran over it and contributed nothing. The one tree
    // whose entire job is to demonstrate that everything passes was not
    // demonstrating that schema conformance passes -- it was silent about it,
    // which reads the same way in the output.
    //
    // Adding the files is not on its own enough, because a fixture that nothing
    // validates against looks identical to one that validates clean. So this is
    // a positive control: break the template inside the materialized copy and
    // the same run has to fail. If it does not, the clean result above is
    // measuring nothing and this test is the only thing that would say so.
    const root = materializeFixture("valid/minimal");
    expect(runValidation(root).issues.filter((i) => i.severity === "error")).toEqual([]);

    writeFileSync(
      join(root, "templates/ticket.json"),
      JSON.stringify({ schema: "ticket", id: 7, title: "wrong type" }),
    );
    const broken = runValidation(root).issues.filter((i) => i.severity === "error");
    expect(broken.map((i) => i.rule)).toContain("schemas.document-invalid");
    expect(broken.some((i) => i.file === "templates/ticket.json")).toBe(true);
  });
});

describe("invalid fixtures", () => {
  for (const c of CASES) {
    test(`${c.tree}: ${c.what}`, () => {
      const errors = errorsOf(`invalid/${c.tree}`, c.schemas);
      const hit = errors.find((i) => i.rule === c.rule && i.file === c.file);
      expect({
        tree: c.tree,
        found: hit !== undefined,
        rules: [...new Set(errors.map((i) => i.rule))].sort(),
      }).toEqual({
        tree: c.tree,
        found: true,
        rules: [...new Set(c.rules ?? [c.rule])].sort(),
      });
      expect(hit?.message).toMatch(c.message);
    });
  }

  test("15-malformed-install measures the real install schema, not a copy that has drifted", () => {
    // The fixture carries its own schemas because a fixture tree is the whole
    // repository the validator sees. What it must not carry is a *different*
    // contract: a stale copy would go on passing while the real schema moved.
    const repo = join(import.meta.dir, "..");
    const fixture = join(import.meta.dir, "fixtures", "invalid", "15-malformed-install");
    expect(readFileSync(join(fixture, "schemas/install.schema.json"), "utf8")).toBe(
      readFileSync(join(repo, "schemas/install.schema.json"), "utf8"),
    );
    const common = (root: string) =>
      JSON.parse(readFileSync(join(root, "schemas/common.schema.json"), "utf8")).$defs.kebab_id;
    expect(common(fixture)).toEqual(common(repo));
  });

  test("every committed invalid fixture has a case asserting what it must report", () => {
    const dir = join(import.meta.dir, "fixtures", "invalid");
    const trees = readdirSync(dir).filter((n) => statSync(join(dir, n)).isDirectory());
    expect(trees.sort()).toEqual(CASES.map((c) => c.tree).sort());
  });
});

describe("the fixtures do not smuggle denied strings into the tree", () => {
  function fixtureFiles(dir: string): string[] {
    const out: string[] = [];
    for (const name of readdirSync(dir)) {
      const full = join(dir, name);
      if (statSync(full).isDirectory()) out.push(...fixtureFiles(full));
      else out.push(full);
    }
    return out;
  }

  test("no committed fixture file contains a denied term or an unfinished marker", () => {
    const terms = [...DENY_TERMS, ...PLACEHOLDER_TERMS];
    const hits: string[] = [];
    for (const file of fixtureFiles(join(import.meta.dir, "fixtures"))) {
      for (const hit of matchTerms(readFileSync(file, "utf8"), terms)) {
        hits.push(`${file}:${hit.line} ${hit.term.id}`);
      }
    }
    expect(hits).toEqual([]);
  });

  test("materializing a fixture substitutes the markers, so the scanner sees the real strings", () => {
    const body = readFileSync(
      join(materializeFixture("invalid/05-model-name-in-body"), "skills/alpha/SKILL.md"),
      "utf8",
    );
    expect(body).not.toContain("__DENY_MODEL_TERM__");
    expect(matchTerms(body, DENY_TERMS).length).toBeGreaterThan(0);
  });
});
